# This is a ci workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Setup environment
        run: |
          go install github.com/wadey/gocovmerge@latest
          go install github.com/mattn/goveralls@latest

      - name: Run go vet
        run: go vet ./...

      - name: Run format check
        run: |
          ./script/format

      - name: Run unit tests
        run: |
          ./script/unittest
          ./script/coverage

      - uses: shogo82148/actions-goveralls@v1.4.5
        with:
          path-to-profile: cover.out
